### PR TITLE
PSR4 Namespacing

### PR DESCRIPTION
**Pull request by addshore**
For https://github.com/addwiki/addwiki/issues/11

### CODE REVIEW

**Comment by addshore** [comment]
@samwilson @JeroenDeDauw I have completed a conversion to PSR4 namespaces.
I'd love some review and thoughts on the namespaces used.
The easiest way to get an overview is https://github.com/addwiki/addwiki/pull/51/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by samwilson** [comment]
Looks good to me, although I'm not sure about the `Mediawiki\Db\` namespace, is there a reason it can't be under `Addwiki\` as well? (I might be misunderstanding things though. Is this the DB namespace *from* MediaWiki?)

**Comment by addshore** [comment]
> Looks good to me, although I'm not sure about the `Mediawiki\Db\` namespace, is there a reason it can't be under `Addwiki\` as well? (I might be misunderstanding things though. Is this the DB namespace *from* MediaWiki?)

Yeah, I accidently left that one in this PR, but I already made another PR to totally remove the DB package anyway.

It was a nice idea but never really used and now just a maintenance burden

**Comment by samwilson** [comment]
Sounds good.

Thanks for working on all this stuff!

**Pull request merged**
