### PR TITLE
OAuth support

### PR DESCRIPTION
**Pull request by addshore**
Fixes https://github.com/addwiki/addwiki/issues/16

### CODE REVIEW

**Comment by addshore** [comment]
Todos:
 [] Actually apply OAuth headers etc
 [] Tests for the AuthMethods
 [] Integration test for the OAuth working...

**Comment by addshore** [comment]
Adding @Tpt and @samwilson to take a look at what this is shaping up to look like.
All thoughts welcome, I'm happy to continue this and merge it myself once I'm happy.
This will make it into the 3.0 release of the libraries.

The login() and logout() etc methods will be removed from the API class.
Instead you will create an API with a AuthMethod which knows what needs to happen.
This will then just work TM, and be flexible to other methods too.

Before 3.0 I'll be updating docs, and making some better factories and convenience methods etc.

**Comment by addshore** [comment]
This is mostly working now, but still got some todos..

- [ ] Make oauth work with POST
- [ ] integration test for oauth with POST
- [ ] Make oauth work with POSTed multipart
- [ ] integration test for oauth with POST multipart
- [ ] Fix mediawiki-api file upload test

The file upload test is broken with:

```
1) Addwiki\Mediawiki\Api\Tests\Integration\Service\FileUploaderTest::testUploadByChunks
Addwiki\Mediawiki\Api\Client\UsageException: Code: badupload
Message: File upload parameter "chunk" is not a file upload; be sure to use multipart/form-data for your POST and include a filename in the Content-Disposition header.
Result: {"error":{"code":"badupload","info":"File upload parameter \"chunk\" is not a file upload; be sure to use multipart\/form-data for your POST and include a filename in the Content-Disposition header.","*":"See http:\/\/localhost:8877\/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https:\/\/lists.wikimedia.org\/mailman\/listinfo\/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes."}}

/home/runner/work/addwiki/addwiki/packages/mediawiki-api-base/src/Client/MediawikiApi.php:371
/home/runner/work/addwiki/addwiki/packages/mediawiki-api-base/src/Client/MediawikiApi.php:236
/home/runner/work/addwiki/addwiki/packages/mediawiki-api-base/src/Client/MediawikiApi.php:223
/home/runner/work/addwiki/addwiki/packages/mediawiki-api/src/Service/FileUploader.php:112
/home/runner/work/addwiki/addwiki/packages/mediawiki-api/src/Service/FileUploader.php:78
/home/runner/work/addwiki/addwiki/packages/mediawiki-api/tests/integration/Service/FileUploaderTest.php:63
```

**Comment by addshore** [comment]
As far as I can tell this PR is now a complete implementation of OAuth1 self owned consumers for MediaWiki :)

**Comment by samwilson** [comment]
Great work!

I've not really reviewed it or anything, but at a glance it looks brill.

**Comment by addshore** [comment]
Awesome! a glance will do!
I have quite a few other changes I want to try to make for a 3.0 release of these things, but I would guess a timeline would be ~1 month right now for having this in a real release

**Pull request merged**
